In [1]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi

%matplotlib inline

In [2]:
load_dotenv()

True

In [3]:
alpaca_api_key=os.getenv("ALPACA_API_KEY")
alpaca_secret_key=os.getenv("ALPACA_SECRET_KEY")
alpaca=tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [4]:
print(alpaca_api_key)
print(alpaca_secret_key)

PKY3SCPEIWRV8EOWGT2O
5Vt54hUeMdDft7frCnriuQmErBQwKAvorGPkDKIa

In [5]:
# Format current date as ISO format
start_d = pd.Timestamp("2022-01-01", tz="America/New_York").isoformat()
end_d = pd.Timestamp("2023-01-01", tz="America/New_York").isoformat()
# Set the tickers
tickers = ["AXP", "RIO"]

# Set timeframe to "1Day" for Alpaca API
timeframe = "1Day"

# Get current closing prices for SPY and AGG
df_portfolio = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_d,
    end = end_d
).df
df_portfolio.drop('trade_count', axis=1, inplace=True)
df_portfolio.drop('vwap', axis=1, inplace=True)

# Reorganize the DataFrame
# Separate ticker data
AXP = df_portfolio[df_portfolio['symbol']=='AXP'].drop('symbol', axis=1)
TSLA = df_portfolio[df_portfolio['symbol']=='RIO'].drop('symbol', axis=1)

# Concatenate the ticker DataFrames
df_portfolio = pd.concat([AXP,TSLA],axis=1, keys=['AXP','RIO'])

# Preview DataFrame
df_portfolio

                              AXP                                         RIO  \
                             open      high       low   close   volume   open
timestamp
2022-01-03 05:00:00+00:00  164.51  168.4000  164.4000  168.21  3121541  67.50
2022-01-04 05:00:00+00:00  169.72  174.0500  169.6000  173.61  4797483  67.20
2022-01-05 05:00:00+00:00  174.71  176.3100  171.5000  171.76  4475495  68.33
2022-01-06 05:00:00+00:00  172.54  173.6900  169.7500  172.90  2642264  70.41
2022-01-07 05:00:00+00:00  172.49  175.3600  171.8601  174.38  3038205  71.19
...                           ...       ...       ...     ...      ...    ...
2022-12-23 05:00:00+00:00  145.23  147.1391  144.5200  147.02  1670668  70.67
2022-12-27 05:00:00+00:00  147.29  147.8600  145.6700  146.39  1855160  71.49
2022-12-28 05:00:00+00:00  146.21  146.8200  143.9400  144.01  1482096  72.03
2022-12-29 05:00:00+00:00  145.08  147.6200  144.4001  147.32  1750463  71.34
2022-12-30 05:00:00+00:00  146.01  147.9300  145.7300  147.75  2228528  70.93


                              high      low  close   volume
timestamp
2022-01-03 05:00:00+00:00  67.6100  66.4200  66.73  3626395
2022-01-04 05:00:00+00:00  68.3299  67.1300  67.52  2983892
2022-01-05 05:00:00+00:00  69.6500  68.3000  68.71  4110568
2022-01-06 05:00:00+00:00  70.5900  69.4600  70.04  4990026
2022-01-07 05:00:00+00:00  72.3300  71.1399  72.24  5408694
...                            ...      ...    ...      ...
2022-12-23 05:00:00+00:00  70.9500  70.3000  70.79  1405711
2022-12-27 05:00:00+00:00  71.8100  71.2300  71.43  1441187
2022-12-28 05:00:00+00:00  72.1400  70.5500  70.63  1884662
2022-12-29 05:00:00+00:00  71.6200  70.9900  71.09  1965154
2022-12-30 05:00:00+00:00  71.5300  70.6007  71.20  1107966

[251 rows x 10 columns]